### ISSUE TITLE
Update drush

### ISSUE THREAD

**Issue by ghost** [aegir-project/development#17]
I use Aegir in Docker for local frontend development extensively but for latest version of Drupal 8 another version of Drush is required. Could you include it in the scripts?

**Comment by helmo** [comment]
That update to the dockerfiles project should do it...

To update a running container you might be able to use `docker exec --user=root -ti aegirdocker_hostmaster_1 bash`
`wget https://github.com/drush-ops/drush/releases/download/8.1.16/drush.phar -O - -q > /usr/local/bin/drush`

**Comment by ghost** [comment]
Thanks, this did it for me
`docker exec --user=root -ti aegirdevelopment_hostmaster_1 bash
wget https://github.com/drush-ops/drush/releases/download/8.1.16/drush.phar -O - -q > /usr/local/bin/drush`

Trying fresh install in latest Docker failed so I stay with Docker 17.09.1-ce-mac42 for now combined with [d4m-nfs](https://github.com/IFSight/d4m-nfs)
This setup works good for theming with Zurb Foundation. For SASS compilation I use [Prepros](https://prepros.io). Version 5 for D7 and version 6 for D8.
