### ISSUE TITLE
Keep database in volume?

### ISSUE THREAD

**Issue by helmo** [aegir-project/development#4]
With the addition of these lines we can get easier access to the mysql database files.

```
    volumes:
      - ./aegir-db:/var/lib/mysql
```

This way even after a 'docker-compose rm'  you get the same installation back. The instructions to destroy would need an extra line to clear the aegir-db directory.

I was discussing with @webfed that this might be an easy way to be able to transfer a development stack between a desktop and laptop.

**Comment by helmo** [comment]
@jonpugh thoughs?

**Comment by jonpugh** [comment]
Seems like a real edge case, one that's easily accomplished with a separate docker-compose.yml file...

In the spirit of keeping the dev environment folder minimal,  I am against using this as the default, but perhaps we add it in some other way, like documentation, a separate docker-compose file, or we could add it to the the docker-compose.yml file, but commented out?

**Comment by helmo** [comment]
OK, I added it but commented out.
